# Pandas

# Series data Structure

The series structure is one of the core data structures in pandas. The items are all stored in an order
and there's labels with which you can retrieve them. 
Two columns of data: the first is the speical index, like key in dictionary. the second is the actual data.
The data column has a label of its own and can be retrieved using the .name attribute.

In [1]:
import pandas as pd

#create a series by passing in a list of values.
#when you do this Pandas automatically assigns an index starting with zero and sets the name of the series to None.

#create an arrar-like object, like a list
students = ['Alice', 'Jack', 'Molly'] #make a list first
#turn that into a series
pd.Series(students)

0    Alice
1     Jack
2    Molly
dtype: object

In [4]:
#the result is a Series object which is nicely rendered to the screen. 
#pandas automatically identified the type of data in this series as 'Object'

#if we passed in a list of whole numbers
numbers = [1, 2, 3]
#and turn that into a series
pd.Series(numbers)

0    1
1    2
2    3
dtype: int64

In [5]:
#how numpy and pandas handle missing data
#we have the none type to indicate a lack of data

students = ['Alice', 'Jack', None]
#And lets convert this to a series
pd.Series(students)

0    Alice
1     Jack
2     None
dtype: object

In [6]:
#if we create a list of numbers, integers or floats, and put in the None type
#pandas automatically converts this to a special floating point value designed as NaN
numbers = [1, 2, None]
#And lets convert this to a series
pd.Series(numbers)

0    1.0
1    2.0
2    NaN
dtype: float64

In [7]:
#'NaN' which stands for 'not a number', it is a special floating point value
#pandas went on and converted the integers to floats.
#when the list of integers you put into a series is not floats, it's probabily because there is some missing data.

In [8]:
#NaN is not equivalent to None
import numpy as np
np.nan == None

False

In [9]:
#you cannot do an equality test of NAN to itself, if you do, the answer is always false
np.nan == np.nan

False

In [12]:
#you need to use some special functions to test for the presence of not a number
#such as the Numpy library isnan()

np.isnan(np.nan)

True

In [13]:
#when you see NaN, it's meaning is similar to None, but it's a numeric value and treated differently for
#efficiency reasons

In [14]:
#a series can be created directly from dictionary data
#the index is automatically assigned to the keys of the dictionary you provided

students_score = {'Alice': 'Physics', 
                 'Jack': 'Chemistry', 
                 'Molly': 'English'}
s = pd.Series(students_score)
s

Alice      Physics
Jack     Chemistry
Molly      English
dtype: object

In [16]:
#index, the first column, is also a list of strings
#we can get the index object using the index attribute

s.index

Index(['Alice', 'Jack', 'Molly'], dtype='object')

In [18]:
#for tuples
students = [('Alice', 'Brown'), ('Jack', 'White'), ('Molly', 'Green')]
pd.Series(students)

0    (Alice, Brown)
1     (Jack, White)
2    (Molly, Green)
dtype: object

In [19]:
#each of the tuples is stored in the series object, and the type is object.

In [20]:
#separate your index creation from the data by passing in the index as a list explicityly to the series
s = pd.Series(['Physics', 'Chemistry', 'English'], index = ['Alice', 'Jack', 'Molly'])
s

Alice      Physics
Jack     Chemistry
Molly      English
dtype: object

In [21]:
#list of values in the index object are not aligned with the keys in the dictionary
#pandas overrides the automatic creation to favour only and all of the indices values that you provided
#pandas will add None or NaN type vlues for any index value you provide, which is not in your dictionary key list

students_score = {'Alice': 'Physics', 
                 'Jack': 'Chemistry', 
                 'Molly': 'English'}
s = pd.Series(students_score, index = ['Alice', 'Molly', 'Sam'])
s

Alice    Physics
Molly    English
Sam          NaN
dtype: object

In [22]:
#the series object doesn't have Jack in it. even though he was in our original dataset.
#it has Sam in it as a missing value

how to create a series from lists, dictionaries and tuples, how indicies on data work, and the way pandas typecasts data including missing values.

# Querying series

The primary data types of the panda library, the Series.

A pandas Series can be queried either by the index position or the index label.
To query by numeric location, starting at zero, use the iloc attribute. To query by the index label, you can use the loc attribute.

In [23]:
import pandas as pd
#use students enrolled in classes coming from a dictionary
students_classes = {'Alice': 'Physics', 
                   'Jack': 'Chemistry', 
                   'Molly': 'English', 
                   'Sam': 'History'}
s = pd.Series(students_classes)
s

Alice      Physics
Jack     Chemistry
Molly      English
Sam        History
dtype: object

In [25]:
#to see the fourth entry, we would use the iloc attribute with the parameter 3

s.iloc[3]

#remember we start from zero

'History'

In [26]:
#to see what class Molly has, we can use the loc attribute with a parameter of Molly

s.loc['Molly']

'English'

In [27]:
#iloc and loc are not methods, they are attributes. so use [] to query them, which is called the index operator

In [28]:
#Pandas provides a sort of smart syntax using the indexing operator directly on the series itself.
#for example, if you pass in an integer parameter, the operator will behave as if you want it to query via the iloc
#attribute

In [30]:
s[3] #s.iloc[3]

'History'

In [31]:
#input an object, it will query as if you want to use the label based loc attribute
s['Molly'] #s.loc['Mooly']

'English'

In [37]:
#index is a list of integers
#Pandas can't determine automaticallly whether you're intending to query by index position or index label.
#safer option would be use the iloc or loc attributes directly

class_code = {99: 'Physics', 
             100: 'Chemistry', 
             101: 'English', 
             102: 'History'}
s = pd.Series(class_code)

#s[0] will raise a key error because there's no item in the classes list with an index of zero

s.iloc[0]

'Physics'

In [38]:
#iterate all the items in the series

grades = pd.Series([90, 80, 70, 60]) #pass a list into series

total = 0
for grade in grades:
    total = total + grade
print(total/len(grades))

75.0

In [39]:
#This works but it's slow.
#Pandas and numpy support a method of computation called vectorization.
#Vectorization works with most of the functions in the numpy library, including the sum function.

In [40]:
#use the numpy sum method
import numpy as np

#Then we just call np.sum and pass in an iterable item. In this case, our panda series.

total = np.sum(grades)
print(total/len(grades))

75.0

In [41]:
#Which one is faster?
#First create a big series of random numbers

In [42]:
numbers = pd.Series(np.random.randint(0, 1000, 10000))
numbers.head() 
#look at top five items in the series to make sure they actually seem random
#we do this with the head() function

0    465
1    430
2    965
3    179
4    842
dtype: int64

In [43]:
#verify the length of the series is correct using len function
len(numbers)

10000

In [44]:
#celluar magic function timeit
#run the code a few times to determine on average how long it takes

In [45]:
%%timeit -n 100 #100 loops
total = 0
for number in numbers:
    total += number
total/len(numbers)

1.16 ms ± 67.5 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)

In [46]:
#Now let's try it with vectorization

In [47]:
%%timeit -n 100
total = np.sum(numbers)
total/len(numbers)

62.3 µs ± 12.6 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)

In [30]:
#speed up in vectorization

In [48]:
#broadcasting
#apply an operation to every value in the series, changing the series.

#look at the head of the series
numbers.head()

0    465
1    430
2    965
3    179
4    842
dtype: int64

In [49]:
# increase everything in the series by 2
numbers = numbers + 2
numbers.head()

0    467
1    432
2    967
3    181
4    844
dtype: int64

In [55]:
#The procedural way of doing this would be to iterate through all of the items in the series and increase the 
#values directly.

#We can use the iteritems() function which returns a label and value

for label, value in numbers.iteritems():
    #now for the item which is returned, lets call set_value
    numbers.at(label, value + 2)
#check the result of this computation
numbers.head()

TypeError: '_AtIndexer' object is not callable

In [56]:
#speed comparisons

In [57]:
%%timeit -n 10
s = pd.Series(np.random.randint(0, 1000, 1000))
for label, value in s.iteritems():
    s.loc[label] = value + 2

39.9 ms ± 1.84 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)

In [58]:
#try that using the broadcasting methods

In [60]:
%%timeit -n 10
s = pd.Series(np.random.randint(0, 1000, 1000))
s+=2 #using broadcasting

331 µs ± 154 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)

In [61]:
#significantly faster, more concise and easier to read too

In [62]:
#using the indexing operators to access series data.
#The loc attribute lets you not only modify data in place, but also add new data as well.
#If the value you pass in as the index doesn't exist, then a new entry is added

In [63]:
s = pd.Series([1, 2, 3]) # a series of a few numbers
#add some new value
s.loc['History'] = 102
s

0            1
1            2
2            3
History    102
dtype: int64

In [64]:
#Mixed types for data values or index labels are no problem for Pandas.

In [65]:
#index values are not unique
students_classes = pd.Series({'Alice': 'Physics', 
                   'Jack': 'Chemistry', 
                   'Molly': 'English', 
                   'Sam': 'History'})
students_classes

Alice      Physics
Jack     Chemistry
Molly      English
Sam        History
dtype: object

In [66]:
#create a series just for some new student Kelly, which lists all of the courses

kelly_classes = pd.Series(['Philosophy', 'Art', 'Math'], index = ['Kelly', 'Kelly', 'Kelly'])
kelly_classes

Kelly    Philosophy
Kelly           Art
Kelly          Math
dtype: object

In [67]:
#append all of the data in this new series to the first using the .append() function

all_students_classes = students_classes.append(kelly_classes)
all_students_classes

Alice       Physics
Jack      Chemistry
Molly       English
Sam         History
Kelly    Philosophy
Kelly           Art
Kelly          Math
dtype: object

In [69]:
#append create a new series and the original series is not changed

In [70]:
#when we query the appended series for Kelly, we get a series itself
all_students_classes.loc['Kelly']

Kelly    Philosophy
Kelly           Art
Kelly          Math
dtype: object

# Data frame data structure

The data frame is conceptually a two-dimensional series object, where there's an index and multiple columns of content, with each column having a label. The distinction between a column and a row is really only a conceptual distinction. And you can think of the DataFrame itself as simply a two-axes labelled array.

In [71]:
import pandas as pd
record1 = pd.Series({'Name': 'Alice', 
                    'Class': 'Physics',
                    'Score': 85})
record2 = pd.Series({'Name': 'Jack', 
                    'Class': 'Chemistry',
                    'Score': 82})
record3 = pd.Series({'Name': 'Helen', 
                    'Class': 'Biology',
                    'Score': 90})

Like a series, the DataFrame object is index. Just like the series function, we can pass in our individual items in an array, and we can pass in our index values as a second arguments

In [72]:
df = pd.DataFrame([record1, record2, record3],
                  index = ['school1', 'school2', 'school1'])
#use the head function to see the first several row of the dataframe, including indices from both axes

df.head()

          Name      Class  Score
school1  Alice    Physics     85
school2   Jack  Chemistry     82
school1  Helen    Biology     90

In [73]:
#index is the leftmost column and is the school name.
# we have rows of data, which each row has a column header which was given in our initial record dictionaries.

In [74]:
#an alternative method is that you could use a list of dictionaries, where each dictionary represents a row of data
students = [{'Name': 'Alice', 
             'Class': 'Physics',
             'Score': 85}, 
            {'Name': 'Jack', 
             'Class': 'Chemistry',
             'Score': 82}, 
            {'Name': 'Helen', 
             'Class': 'Biology',
             'Score': 90} ]

#We pass the list of dictionaries into the DataFrame function

df = pd.DataFrame(students, index = ['school1', 'school2', 'school1'])
df.head()

          Name      Class  Score
school1  Alice    Physics     85
school2   Jack  Chemistry     82
school1  Helen    Biology     90

In [75]:
#We can extract data using the iloc and loc attributes
#Because it is two-dimensional, passing a single value to the loc indexing operator will return the series if there
#is only one row to return

#select data associated to school2, we just query the .loc attribute with one parameter

df.loc['school2']

Name          Jack
Class    Chemistry
Score           82
Name: school2, dtype: object

In [76]:
type(df.loc['school2'])

pandas.core.series.Series

In [77]:
df.loc['school1']

          Name    Class  Score
school1  Alice  Physics     85
school1  Helen  Biology     90

In [78]:
#and we can see that the type is different too
type(df.loc['school1'])

pandas.core.frame.DataFrame

In [79]:
#dataframe - you can quickly select data based on multiple axes
#supply two parameters to .loc, one being the row index and the other being the column name

df.loc['school1', 'Name']

school1    Alice
school1    Helen
Name: Name, dtype: object

In [80]:
#if we want to select a single column
#first, we could transpose the matrix, this pivots all of the rows into columns and all of the columns into rows
#it is done with the T attribute

df.T

       school1    school2  school1
Name     Alice       Jack    Helen
Class  Physics  Chemistry  Biology
Score       85         82       90

In [81]:
#Then we can call .loc on the transpose to get the students names only

df.T.loc['Name']

school1    Alice
school2     Jack
school1    Helen
Name: Name, dtype: object

In [82]:
#iloc and loc are used for row selection. Panda reserves the indexing operator directly on the DataFrame for column
#selection. So this selection is always label based, and is not as confusing as it was when using the square
#bracket operator on the series objects.

In [83]:
df['Name']

school1    Alice
school2     Jack
school1    Helen
Name: Name, dtype: object

In [ ]:
df.loc['Name']
#get a key error if you try and use loc with a column name

In [84]:
#The result of a single column projection is a Series object

type(df['Name'])

pandas.core.series.Series

In [85]:
#chain operations together

df.loc['school1']['Name']
#school the row, name the column

school1    Alice
school1    Helen
Name: Name, dtype: object

In [86]:
print(type(df.loc['school1']))
print(type(df.loc['school1']['Name']))

<class 'pandas.core.frame.DataFrame'>
<class 'pandas.core.series.Series'>

In [87]:
#Chaining can come with some costs and is best avoided if you can use another approach.
#If you are changing data though this is an important distinction and can be a source of error

In [88]:
#Here's another approach, use .loc
#row selection, take two parameters, the row index and the list of column names
#The loc attribute also supports slicing.

df.loc[:, ['Name', 'Score']]

          Name  Score
school1  Alice     85
school2   Jack     82
school1  Helen     90

The colon means that we want to get all of the rows, and the list in the second argument position is the list of columns we want to get back

In [89]:
#drop fuction returns you a copy of the dataframe with the given rows removed

df.drop('school1')

         Name      Class  Score
school2  Jack  Chemistry     82

In [90]:
#the original data is still intact.
df

          Name      Class  Score
school1  Alice    Physics     85
school2   Jack  Chemistry     82
school1  Helen    Biology     90

optional parameters in drop.
First one is inplace, and if it is set to true, the dataframe will be updated in place, instead of a copy being returned.
Second one is the axes, which should be dropped. default = 0 indicating the row axis. but you can change it to 1 if you want to drop a column.

In [91]:
copy_df = df.copy()
#drop the name column in this copy
copy_df.drop('Name', inplace = True, axis = 1)
copy_df

             Class  Score
school1    Physics     85
school2  Chemistry     82
school1    Biology     90

In [92]:
#a second way to drop a column, and that's directly through the use of indexing operator, using the del keyword
del copy_df['Class']
copy_df

         Score
school1     85
school2     82
school1     90

In [93]:
#add a new column to the dataframe
df['ClassRanking'] = None
df

          Name      Class  Score ClassRanking
school1  Alice    Physics     85         None
school2   Jack  Chemistry     82         None
school1  Helen    Biology     90         None

# DataFrame indexing and loading

How to load data from a comma separated file into a DataFrame

In [2]:
!cat datesets/Admission_Predict.csv

'cat' is not recognized as an internal or external command,
operable program or batch file.

In [4]:
#turn a CSV into a dataFrame
df = pd.read_csv('E:\\Academics\\python\\applied data science in python\\introduction to data science to python\\week 2\\Admission_Predict.csv')
#call the first few 
df.head()

,Serial No.,GRE Score,TOEFL Score,University Rating,SOP,LOR,CGPA,Research,Chance of Admit
0,1,337,118,4,4.5,4.5,9.65,1,0.92
1,2,324,107,4,4.0,4.5,8.87,1,0.76
2,3,316,104,3,3.0,3.5,8.00,1,0.72
3,4,322,110,3,3.5,2.5,8.67,1,0.80
4,5,314,103,2,2.0,3.0,8.21,0,0.65

In [5]:
#set the serial no. as the index
df = pd.read_csv('E:\\Academics\\python\\applied data science in python\\introduction to data science to python\\week 2\\Admission_Predict.csv', index_col = 0)
df.head()

,GRE Score,TOEFL Score,University Rating,SOP,LOR,CGPA,Research,Chance of Admit
Serial No.,,,,,,,,
1,337,118,4,4.5,4.5,9.65,1,0.92
2,324,107,4,4.0,4.5,8.87,1,0.76
3,316,104,3,3.0,3.5,8.00,1,0.72
4,322,110,3,3.5,2.5,8.67,1,0.80
5,314,103,2,2.0,3.0,8.21,0,0.65

In [8]:
#change the column names to make SOP and LOR more clear
new_df = df.rename(columns = {'GRE Score': 'GRE Score', 'TOEFL Score': 'TOEFL Score', 'University Rating': 'University Rating', 'SOP': 'Statement of Purpose', 'LOR': 'Letter of Recommendation', 
'CGPA': 'CGPA', 'Research': 'Research', 'Chance of Admit': 'Chance of Admit'})
new_df.head()

,GRE Score,TOEFL Score,University Rating,Statement of Purpose,LOR,CGPA,Research,Chance of Admit
Serial No.,,,,,,,,
1,337,118,4,4.5,4.5,9.65,1,0.92
2,324,107,4,4.0,4.5,8.87,1,0.76
3,316,104,3,3.0,3.5,8.00,1,0.72
4,322,110,3,3.5,2.5,8.67,1,0.80
5,314,103,2,2.0,3.0,8.21,0,0.65

In [9]:
#We can see that only the SOP is changed not LOR
#First we need to make sure we got all the columns names correct
#We can use the columns attribute of dataframe to get a list 

new_df.columns

Index(['GRE Score', 'TOEFL Score', 'University Rating', 'Statement of Purpose',
       'LOR ', 'CGPA', 'Research', 'Chance of Admit '],
      dtype='object')

In [12]:
#we can find a space after LOR and a space after Chance of Admit
#the key we used was just three characters, instead of 'LOR'
#we can include the space in the new name

new_df = new_df.rename(columns = {'LOR': 'Letter of Recommendation'})
new_df.head()

,GRE Score,TOEFL Score,University Rating,Statement of Purpose,Letter of Recommendation,CGPA,Research,Chance of Admit
Serial No.,,,,,,,,
1,337,118,4,4.5,4.5,9.65,1,0.92
2,324,107,4,4.0,4.5,8.87,1,0.76
3,316,104,3,3.0,3.5,8.00,1,0.72
4,322,110,3,3.5,2.5,8.67,1,0.80
5,314,103,2,2.0,3.0,8.21,0,0.65

In [13]:
#What if there is a tab instead of a space?
#strip white space: strip()

new_df = new_df.rename(mapper = str.strip, axis = 'columns')
new_df.head()

,GRE Score,TOEFL Score,University Rating,Statement of Purpose,Letter of Recommendation,CGPA,Research,Chance of Admit
Serial No.,,,,,,,,
1,337,118,4,4.5,4.5,9.65,1,0.92
2,324,107,4,4.0,4.5,8.87,1,0.76
3,316,104,3,3.0,3.5,8.00,1,0.72
4,322,110,3,3.5,2.5,8.67,1,0.80
5,314,103,2,2.0,3.0,8.21,0,0.65

In [14]:
#The rename function does not modify the dataframe. There is just a copy in new_df with the changed names
df.columns

Index(['GRE Score', 'TOEFL Score', 'University Rating', 'SOP', 'LOR ', 'CGPA',
       'Research', 'Chance of Admit '],
      dtype='object')

In [15]:
#We can also use the df.columns attribute by assigning to it a list of column names which will directly rename the columns
#This will directly modify the original dataframe

#Let's change all of the columns names to lower case
cols = list(df.columns)
#Then a little list comprehension
cols = [x.lower().strip() for x in cols]
#Then we just overwrite what is already in the column attribute
df.columns = cols
df.head()

,gre score,toefl score,university rating,sop,lor,cgpa,research,chance of admit
Serial No.,,,,,,,,
1,337,118,4,4.5,4.5,9.65,1,0.92
2,324,107,4,4.0,4.5,8.87,1,0.76
3,316,104,3,3.0,3.5,8.00,1,0.72
4,322,110,3,3.5,2.5,8.67,1,0.80
5,314,103,2,2.0,3.0,8.21,0,0.65

# Querying a DataFrame

The first step in the process is to understand Boolean masking.
Boolean masking is the heart of fast and efficient querying in numpy and pandas

In [3]:
import pandas as pd 
df = pd.read_csv('E:\\Academics\\python\\applied data science in python\\introduction to data science to python\\week 2\\Admission_Predict.csv', index_col = 0)
df.columns = [x.lower().strip() for x in df.columns]
df.head()

,gre score,toefl score,university rating,sop,lor,cgpa,research,chance of admit
Serial No.,,,,,,,,
1,337,118,4,4.5,4.5,9.65,1,0.92
2,324,107,4,4.0,4.5,8.87,1,0.76
3,316,104,3,3.0,3.5,8.00,1,0.72
4,322,110,3,3.5,2.5,8.67,1,0.80
5,314,103,2,2.0,3.0,8.21,0,0.65

In [4]:
#Boolean masks are created by applying operators directly to the pandas series or dataframe objects

#To build a Boolean mask for this query
admit_mask = df['chance of admit'] > 0.7
admit_mask

Serial No.
1       True
2       True
3       True
4       True
5      False
       ...
396     True
397     True
398     True
399    False
400     True
Name: chance of admit, Length: 400, dtype: bool

In [5]:
# So, what do you do with the boolean mask once you have formed it? Well, you can just lay it on top of the
# data to "hide" the data you don't want, which is represented by all of the False values. We do this by using
# the .where() function on the original DataFrame.
df.where(admit_mask).head()

,gre score,toefl score,university rating,sop,lor,cgpa,research,chance of admit
Serial No.,,,,,,,,
1,337.0,118.0,4.0,4.5,4.5,9.65,1.0,0.92
2,324.0,107.0,4.0,4.0,4.5,8.87,1.0,0.76
3,316.0,104.0,3.0,3.0,3.5,8.00,1.0,0.72
4,322.0,110.0,3.0,3.5,2.5,8.67,1.0,0.80
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
#Only data which met the condition was retained. All of the rows which did not meet the condition have NaN data instead
#If we don't want the NaN data, we use dropna() function

df.where(admit_mask).dropna().head()

,gre score,toefl score,university rating,sop,lor,cgpa,research,chance of admit
Serial No.,,,,,,,,
1,337.0,118.0,4.0,4.5,4.5,9.65,1.0,0.92
2,324.0,107.0,4.0,4.0,4.5,8.87,1.0,0.76
3,316.0,104.0,3.0,3.0,3.5,8.00,1.0,0.72
4,322.0,110.0,3.0,3.5,2.5,8.67,1.0,0.80
6,330.0,115.0,5.0,4.5,3.0,9.34,1.0,0.90

In [7]:
#a shorthead syntax which combines where() and dropna(), doing both at once
df[df['chance of admit'] >0.7].head()

,gre score,toefl score,university rating,sop,lor,cgpa,research,chance of admit
Serial No.,,,,,,,,
1,337,118,4,4.5,4.5,9.65,1,0.92
2,324,107,4,4.0,4.5,8.87,1,0.76
3,316,104,3,3.0,3.5,8.00,1,0.72
4,322,110,3,3.5,2.5,8.67,1,0.80
6,330,115,5,4.5,3.0,9.34,1,0.90

In [8]:
#called with a string parameter to project a single column

df['gre score'].head()

Serial No.
1    337
2    324
3    316
4    322
5    314
Name: gre score, dtype: int64

In [9]:
#Or you can send it a list of columns as strings

df[['gre score', 'toefl score']].head()

            gre score  toefl score
Serial No.
1                 337          118
2                 324          107
3                 316          104
4                 322          110
5                 314          103

In [10]:
#or you can send it a boolean mask

df[df['gre score']>320].head()

,gre score,toefl score,university rating,sop,lor,cgpa,research,chance of admit
Serial No.,,,,,,,,
1,337,118,4,4.5,4.5,9.65,1,0.92
2,324,107,4,4.0,4.5,8.87,1,0.76
4,322,110,3,3.5,2.5,8.67,1,0.80
6,330,115,5,4.5,3.0,9.34,1,0.90
7,321,109,3,3.0,4.0,8.20,1,0.75

In [ ]:
#combining multiple boolean masks, such as multiple criteria for including
(df['chance of admit']>0.7) and (df['chance of admit']<0.9)
#produce a traceback

In [11]:
(df['chance of admit']>0.7) & (df['chance of admit']<0.9)

Serial No.
1      False
2       True
3       True
4       True
5      False
       ...
396     True
397     True
398    False
399    False
400    False
Name: chance of admit, Length: 400, dtype: bool

In [12]:
#get rid of the comparison operator completely, and instead use the built in function

df['chance of admit'].gt(0.7) & df['chance of admit'].lt(0.9)

Serial No.
1      False
2       True
3       True
4       True
5      False
       ...
396     True
397     True
398    False
399    False
400    False
Name: chance of admit, Length: 400, dtype: bool

In [13]:
df['chance of admit'].gt(0.7).lt(0.9)

Serial No.
1      False
2      False
3      False
4      False
5       True
       ...
396    False
397    False
398    False
399     True
400    False
Name: chance of admit, Length: 400, dtype: bool

In [14]:
#This only works if your operator, such as less than or greater than, is built into the dataframe

# Indexing Dataframes

Indices can either be either autogenerated, such as when 
we create a new Series without an index, in which case we get numeric values, or they can be set explicitly, like
when we use the dictionary object to create the series, or when we loaded data from the CSV file and set 
appropriate parameters. Another option for setting an index is to use the set_index() function.

In [15]:
# The set_index() function is a destructive process, and it doesn't keep the current index. 
# If you want to keep the current index, you need to manually create a new column and copy into 
# it values from the index attribute.

import pandas as pd 
df =  pd.read_csv('E:\\Academics\\python\\applied data science in python\\introduction to data science to python\\week 2\\Admission_Predict.csv', index_col = 0)
df.head()

,GRE Score,TOEFL Score,University Rating,SOP,LOR,CGPA,Research,Chance of Admit
Serial No.,,,,,,,,
1,337,118,4,4.5,4.5,9.65,1,0.92
2,324,107,4,4.0,4.5,8.87,1,0.76
3,316,104,3,3.0,3.5,8.00,1,0.72
4,322,110,3,3.5,2.5,8.67,1,0.80
5,314,103,2,2.0,3.0,8.21,0,0.65